//dados
const proffys = [ //array
    //{name, avatar, whatsapp, bio, subject, cost, weekday, time_from, time_to}//obj
    {
        name: 'Thiago Guimaraes', 
        avatar: "https://scontent.fcgh7-1.fna.fbcdn.net/v/t1.0-9/59735_164794737008058_1878412118_n.jpg?_nc_cat=100&_nc_sid=09cbfe&_nc_eui2=AeFEXHJVOoGBV6Ry5iU56N8MpA6nbK8Aeo6kDqdsrwB6jl1ZqubtKlKR6WBeMX9dJqNRDyjt8iRFT0AaSi6PR1Io&_nc_ohc=mI2JxiYXcpcAX9qHcbV&_nc_ht=scontent.fcgh7-1.fna&oh=198fb88278367f76a9a4a82714435419&oe=5F537EC0", 
        whatsapp: "11993086372", 
        bio:"Especialista em jogos online. venha comigo jogar LOL, Fortnite e Valorant", 
        subject:"Games Online", 
        cost:"999,99", 
        weekday: [0] , //domingo 
        time_from:[720], //
        time_to: [1220]  //
    },

    {
        name: 'Tur Guima', 
        avatar: "https://scontent.fcgh7-1.fna.fbcdn.net/v/t1.0-9/42792870_1693242554120211_6500279642098761728_n.jpg?_nc_cat=107&_nc_sid=174925&_nc_eui2=AeHIzBk1eyLfecudgeYSKEz-eQ0gKV0AW0V5DSApXQBbReCtmo7aIDg5RH_Emwz4IoNNPS7SEAHE08D1r6o7CCAb&_nc_ohc=oc4qlTK3XJgAX_lipH-&_nc_ht=scontent.fcgh7-1.fna&oh=4b9ade282728c4fcfd4ef7d413523f58&oe=5F542C68", 
        whatsapp: "11993086372", 
        bio:"Especialista em ... isso mesmo que vc tá pensando .¬¬", 
        subject:"Analzinho com prazer", 
        cost:"999,99", 
        weekday: [0] , //domingo 
        time_from:[720], //
        time_to: [1220]  //
    }
]
